version: '3.8'

services:

  backend:
    build: 
      context: ./enap_backend
      dockerfile: Dockerfile
    command: ./wait-for-it.sh postgres:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./enap_backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-8x#m8$3p9v2n1q5r7t9y1b3n5m7k9j1h3g5f7d9s1a3p5o7i9u8y6t4r2e1w3q5
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - POSTGRES_DB=stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DEFAULT_FROM_EMAIL=noreply@enap.dz
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: stockify_postgres
    environment:
      POSTGRES_DB: stockify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for caching and Celery
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Celery worker
  celery:
    build: 
      context: ./enap_backend
      dockerfile: Dockerfile
    command: celery -A stockify worker -l INFO
    volumes:
      - ./enap_backend:/app
    environment:
      - DEBUG=1
      - POSTGRES_DB=stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  # Celery beat for scheduled tasks
  celery-beat:
    build: 
      context: ./enap_backend
      dockerfile: Dockerfile
    command: celery -A stockify beat -l INFO
    volumes:
      - ./enap_backend:/app
    environment:
      - DEBUG=1
      - POSTGRES_DB=stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_node_modules: 