# Generated by Django 5.2.1 on 2025-05-26 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('comptable', 'Comptable'), ('rh', 'Human Resources'), ('terminal_user', 'Terminal User'), ('client_industriel', 'Industrial Client'), ('client_point_vente', 'Retail Point'), ('client_revendeur', 'Reseller Client')], default='client_point_vente', max_length=20, verbose_name='user type')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('image', models.ImageField(blank=True, help_text='Supported formats: JPEG, PNG, BMP', upload_to='users/images/', verbose_name='profile image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_sso_authenticated', models.BooleanField(default=False, verbose_name='SSO authenticated')),
                ('last_password_reset_request', models.DateTimeField(blank=True, null=True, verbose_name='last password reset request')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='IndustrialClient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('company_address', models.TextField(verbose_name='company address')),
                ('company_id', models.CharField(max_length=50, verbose_name='company ID')),
                ('contact_person', models.CharField(max_length=255, verbose_name='contact person')),
                ('delivery_addresses', models.JSONField(default=list, verbose_name='delivery addresses')),
                ('payment_terms', models.CharField(max_length=255, verbose_name='payment terms')),
                ('client_category', models.CharField(choices=[('industriel', 'Industrial'), ('revendeur', 'Reseller')], max_length=20, verbose_name='client category')),
                ('sector_activity', models.CharField(max_length=100, verbose_name='sector of activity')),
                ('is_priority_client', models.BooleanField(default=False, verbose_name='priority client')),
                ('contract_reference', models.CharField(blank=True, max_length=100, verbose_name='contract reference')),
            ],
            options={
                'verbose_name': 'industrial client',
                'verbose_name_plural': 'industrial clients',
            },
            bases=('users.user', models.Model),
        ),
        migrations.CreateModel(
            name='ResellerClient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('company_address', models.TextField(verbose_name='company address')),
                ('company_id', models.CharField(max_length=50, verbose_name='company ID')),
                ('contact_person', models.CharField(max_length=255, verbose_name='contact person')),
                ('delivery_addresses', models.JSONField(default=list, verbose_name='delivery addresses')),
                ('payment_terms', models.CharField(max_length=255, verbose_name='payment terms')),
                ('client_category', models.CharField(choices=[('industriel', 'Industrial'), ('revendeur', 'Reseller')], max_length=20, verbose_name='client category')),
                ('resale_area', models.CharField(max_length=255, verbose_name='resale area')),
                ('monthly_estimate', models.FloatField(default=0.0, verbose_name='monthly estimate')),
                ('has_resale_agreement', models.BooleanField(default=False, verbose_name='has resale agreement')),
            ],
            options={
                'verbose_name': 'reseller client',
                'verbose_name_plural': 'reseller clients',
            },
            bases=('users.user', models.Model),
        ),
        migrations.CreateModel(
            name='RetailPoint',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('store_manager_name', models.CharField(max_length=255, verbose_name='store manager name')),
                ('store_code', models.CharField(max_length=50, unique=True, verbose_name='store code')),
                ('assigned_region', models.CharField(max_length=255, verbose_name='assigned region')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='opening hours')),
            ],
            options={
                'verbose_name': 'retail point',
                'verbose_name_plural': 'retail points',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'administrator',
                'verbose_name_plural': 'administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='ComptableUser',
            fields=[
            ],
            options={
                'verbose_name': 'comptable',
                'verbose_name_plural': 'comptables',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='RHUser',
            fields=[
            ],
            options={
                'verbose_name': 'human resources',
                'verbose_name_plural': 'human resources',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'super administrator',
                'verbose_name_plural': 'super administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='TerminalUser',
            fields=[
            ],
            options={
                'verbose_name': 'terminal user',
                'verbose_name_plural': 'terminal users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
