# Generated by Django 5.2.1 on 2025-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.CreateModel(
            name='DirectorUser',
            fields=[
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('director', 'Director'), ('comptable', 'Comptable'), ('rh', 'Human Resources'), ('terminal_user', 'Terminal User'), ('client_industriel', 'Industrial Client'), ('client_point_vente', 'Retail Point'), ('client_revendeur', 'Reseller Client')], default='client_point_vente', max_length=20, verbose_name='user type'),
        ),
    ]
