# Generated by Django 5.2.1 on 2025-05-30 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emballage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emballage',
                'verbose_name_plural': 'Emballages',
            },
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gamme',
                'verbose_name_plural': 'Gammes',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='products.gamme')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.IntegerField(default=0)),
                ('poids_emballage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couleurs', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('date_fabrication', models.DateField()),
                ('date_expiration', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emballage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.emballage')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.famille')),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.gamme')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
    ]
